deprecate port and add ip

diff --git a/build/dpkg/DEBIAN/postinst b/build/dpkg/DEBIAN/postinst
--- a/build/dpkg/DEBIAN/postinst
+++ b/build/dpkg/DEBIAN/postinst
@@ -1,17 +1,64 @@
 #!/bin/bash
+# postinst for docker-dns
 
-#postinst
-PATH=$PATH:/bin:/usr/bin:/sbin/:/usr/sbin
+PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
 SERVICE_NAME=docker-dns
+CONFIG_FILE="/etc/docker-dns/docker-dns.conf"
+
+get_custom_ip() {
+    if [ -f "$CONFIG_FILE" ]; then
+        custom_ip=$(grep '^IP=' "$CONFIG_FILE" | head -n1 | cut -d'=' -f2)
+        echo "$custom_ip"
+    else
+        echo ""
+    fi
+}
 
 case $1 in
 configure)
-  if [[ "$( ps -p 1 -o comm=)" != "systemd" ]]; then
-    echo "Failed to detect systemd, aborting installation"
-    exit 1;
-  fi
+    if [[ "$(ps -p 1 -o comm=)" != "systemd" ]]; then
+        echo "Failed to detect systemd, aborting installation"
+        exit 1
+    fi
+
     systemctl daemon-reload
+
     systemctl start "${SERVICE_NAME}.service"
     systemctl enable "${SERVICE_NAME}.service"
+
+    CUSTOM_IP=$(get_custom_ip)
+    if [ -z "$CUSTOM_IP" ]; then
+        echo "No 'IP' defined in ${CONFIG_FILE}. Aborting DNS configuration."
+        exit 1
+    fi
+
+    if systemctl is-active systemd-resolved.service >/dev/null 2>&1; then
+        echo "Detected systemd-resolved running. Extending its configuration.."
+
+        if [ ! -d /etc/systemd/resolved.conf.d ]; then
+            echo "Creating /etc/systemd/resolved.conf.d folder.."
+            mkdir -p /etc/systemd/resolved.conf.d
+        fi
+        echo "Creating /etc/systemd/resolved.conf.d/docker-dns.conf.."
+        cat <<EOF >/etc/systemd/resolved.conf.d/docker-dns.conf
+[Resolve]
+# Prepend docker-dns IP to the DNS list.
+DNS=$CUSTOM_IP
+EOF
+        systemctl restart systemd-resolved.service
+        echo "systemd-resolved extended with DNS=$CUSTOM_IP."
+    else
+        echo "systemd-resolved is not active. Updating /etc/resolv.conf.."
+        (cat /etc/resolv.conf | grep -q $CUSTOM_IP) && (echo "detected an entry of $CUSTOM_IP in /etc/resolv.conf, removing.." && sudo sed -i "/$CUSTOM_IP/d" "/etc/resolv.conf")
+        cat <<EOF >>/etc/resolv.conf
+# Generated by docker-dns
+nameserver $CUSTOM_IP
+EOF
+        echo "/etc/resolv.conf updated with nameserver $CUSTOM_IP."
+    fi
+    ;;
+*)
+    echo "Usage: $0 configure"
+    exit 1
     ;;
 esac
