Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -173,9 +173,9 @@ jobs:
           podman exec ${{ env.CONTAINER_NAME }} sleep 1
       - name: Test Direct Internal Resolution
         run: |
-          podman exec ${{ env.CONTAINER_NAME }} address="$(dig @127.0.0.153 nginx.docker +short | head -1 || (echo "Internal DNS resolution against 127.0.0.153 failed" && exit 1))"
-          podman exec ${{ env.CONTAINER_NAME }} [[ $address =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] || (echo "Internal DNS resolution against 127.0.0.153 returned an unexpected value" && exit 1)
-          podman exec ${{ env.CONTAINER_NAME }} echo "nginx.docker : $address"
+          address="$(podman exec ${{ env.CONTAINER_NAME }} dig @127.0.0.153 nginx.docker +short | head -1 || (echo "Internal DNS resolution against 127.0.0.153 failed" && exit 1))"
+          [[ $address =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] || (echo "Internal DNS resolution against 127.0.0.153 returned an unexpected value" && exit 1)
+          echo "nginx.docker : $address"
       - name: Test Integrated Internal Resolution (systemd-resolved)
         run: |          
           podman exec ${{ env.CONTAINER_NAME }} address="$(dig nginx.docker +short | head -1 || (echo "Internal DNS resolution through systemd-resolved failed" && exit 1))"
